### ISSUE TITLE
adding new attributes to genome config file format

### ISSUE THREAD

**Issue by nsheff** [databio/refgenieserver#7]
we originally described the format as just one layer deep: https://github.com/databio/refgenie/issues/6

like: 

```
# Genome configuration

genome_folder: $GENOMES
genome_server: http://localhost

genomes:
  hg38:
    bowtie2: indexed_bowtie2
    hisat2: indexed_hisat2
    tss_annotation: TSS.bed.gz
    gtf: blah.gtf
  mm10:
    bowtie2: indexed_bowtie2
    blacklist: blacklist/mm10.bed
 
  rCRSd:
    bowtie2: indexed_bowtie2
```

but the server requires a bit more information: the archive folder at the project level, and then for individual assets we need filesize, checksum, etc. So for server we need a bit more info. I therefore propose this format:

```
# Genome configuration

genome_folder: $GENOMES
genome_server: http://localhost
genome_archive: /path/to/archives

genomes:
  hg38:
    bowtie2:
      path: indexed_bowtie2
      archive_checksum: mm20349234n20349280345mv2035
      asset_size: 32G
      archive_size: 7G
    hisat2:
      path: indexed_hisat2
      archive_checksum: mm20349234n20349280345mv2035
      asset_size: 12G
      archive_size: 4G
    tss_annotation:
      path: TSS.bed.gz
      archive_checksum: mm20349234n20349280345mv2035
      asset_size: 21M
      archive_size: 3M 
```
